name = "ring"
version = "0.1.0"
defaultTargets = ["test"]

[[require]]
name = "llmlean"
# path = "../llmlean"
git = "https://github.com/fbundle/llmlean.git"
rev = "a76a665c58a59e813918f16b51993ccc81bc6ae2"


[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5e932f97dd25535344f80f9dd8da3aab83df0fe6"


[[lean_lib]]
name = "Ring"

[[lean_exe]]
name = "test"
root = "Main"
